// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Lobby struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	HostID     uuid.UUID
	InviteCode string
	MaxUsers   int32
	StartedAt  sql.NullTime
	EndedAt    sql.NullTime
	Status     string
}

type LobbyUser struct {
	LobbyID  uuid.UUID
	UserID   uuid.UUID
	JoinedAt time.Time
	Role     string
}

type Problem struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Title         string
	Description   string
	Difficulty    string
	StarterCode   string
	TimeLimit     int32
	MemoryLimitMb int32
}

type ProblemTest struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ProblemID uuid.UUID
	TestCode  string
}

type Submission struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UserID    uuid.UUID
	ProblemID uuid.UUID
	Code      string
	Language  string
	Status    string
	RuntimeMs sql.NullInt32
	MemoryKb  sql.NullInt32
	Output    sql.NullString
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	Email        string
	PasswordHash string
	LastLoginAt  sql.NullTime
	Role         string
}
